[resizetizer] non-vector images should not resize by default (#6419)
Fixes the Android side of:

https://github.com/dotnet/maui/issues/5938

On Android, the linked sample crashes with:

    Java.Lang.RuntimeException: 'Canvas: trying to draw too large(485897280bytes) bitmap.

It appears like this image is simply too big:

1. The image starts at 3008x5340

2. MAUI's build upscales this to 21360x12032, see
   `obj\Debug\net6.0-android\resizetizer\r\drawable-xxxhdpi`

A workaround is to do:

    <MauiImage Update="Resources\Images\large.jpg" Resize="false" />

Let's make `%(Resize)` of `false` be the default for non-vector
images. If users specify `%(BaseSize)` or `%(Resize)` themselves, then
we'll continue to use those settings.

I updated some tests around this scenario.

This has both app size and performance implications for all platforms
-- as usage of `.png` or `.jpg` file will no longer get upscaled to
enormous dimensions. Yay!