[android] 20250618 net10.0 ecosystem updates (#30059)
* [android] 20250618 net10.0 ecosystem updates

This is WIP, it currently errors with:

    src\Core\src\Handlers\Toolbar\ToolbarHandler.Android.cs(101,21): error CS7069: Reference to type 'ISavedStateRegistryOwner' claims it is defined in 'Xamarin.AndroidX.SavedState', but it could not be found
    src\Core\src\Platform\Android\MauiAppCompatActivity.cs(43,6): error CS7069: Reference to type 'ISavedStateRegistryOwner' claims it is defined in 'Xamarin.AndroidX.SavedState', but it could not be found
    src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs(468,9): error CS7069: Reference to type 'ISavedStateRegistryOwner' claims it is defined in 'Xamarin.AndroidX.SavedState', but it could not be found
    src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs(468,9): error CS8602: Dereference of a possibly null reference.
    src\Core\src\Platform\Android\ContextExtensions.cs(467,9): error CS7069: Reference to type 'ISavedStateRegistryOwner' claims it is defined in 'Xamarin.AndroidX.SavedState', but it could not be found

This mainly updates Xamarin.AndroidX.Navigation.* packages to a new
2.9.0 version from Google.

Going a step further from the recent update in db65c138, I continued
to refactor and remove MSBuild properties like
`$(_XamarinAndroidGlideVersion)` that dependabot won't be able to
update.

Removed:

* `$(_XamarinAndroidGlideVersion)`
* `$(_XamarinAndroidXSecurityVersion)`
* `$(_XamarinGoogleCryptoTinkAndroidVersion)`
* `$(XamarinGooglePlayServicesMaps)`

The versions of these packages are now tracked in a single location,
`AndroidX.targets`, that dependabot can update. Example [here][0].

[0]: https://github.com/jonathanpeppers/boots/commit/c190ed4e5ef8977d5af93877a889919a3f0ade19

* Incremental AndroidX updates

* Xamarin.AndroidX.SavedState 1.3.0.1