[main] Update dependencies from xamarin/xamarin-android (#1443)
* Update dependencies from https://github.com/xamarin/xamarin-android build 6.0.1xx-preview6-03b91941bf31a562b3243d3ac76846f0bac71636-1

Microsoft.Android.Sdk.Windows
 From Version 30.0.100-preview.6.51 -> To Version 30.0.100-preview.6.53

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref
 From Version 6.0.100-preview.6.21313.2 -> To Version 6.0.100-preview.6.21323.1 (parent: Microsoft.Android.Sdk.Windows

* [build] set %TEMP% and %TMP%

Context: https://github.com/dotnet/sdk/issues/18516

Attempts to workaround the failure:

    > D:\agent\1\s\bin\dotnet\dotnet workload install microsoft-android-sdk-full --skip-manifest-update --verbosity diag
    ...
    Workload installation failed: Source and destination path must have identical roots. Move will not work across volumes.

If `dotnet` is in `D:\agent\1\s\bin\dotnet\dotnet` and `%TEMP%` is
`C:\Users\XAMARI~1\AppData\Local\Temp`, this seems to fail.

Setting `%TEMP%` to `.\bin\temp` in the current directory instead.

* Update dependencies from https://github.com/xamarin/xamarin-android build 6.0.1xx-preview6-d515a1c8112c700ae9f22f9c27829cf54a79931e-1

Microsoft.Android.Sdk.Windows
 From Version 30.0.100-preview.6.51 -> To Version 30.0.100-preview.6.54

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref
 From Version 6.0.100-preview.6.21313.2 -> To Version 6.0.100-preview.6.21323.1 (parent: Microsoft.Android.Sdk.Windows

* Update dependencies from https://github.com/xamarin/xamarin-android build 6.0.1xx-preview6-9bc7166b808aa4c4456c960adb127970d9580fa1-1

Microsoft.Android.Sdk.Windows
 From Version 30.0.100-preview.6.51 -> To Version 30.0.100-preview.6.55

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref
 From Version 6.0.100-preview.6.21313.2 -> To Version 6.0.100-preview.6.21324.9 (parent: Microsoft.Android.Sdk.Windows

* Update dependencies from https://github.com/xamarin/xamarin-android build 6.0.1xx-preview6-f57c5c2a195d47a699a4043aa7ba5b3000278531-1

Microsoft.Android.Sdk.Windows
 From Version 30.0.100-preview.6.51 -> To Version 30.0.100-preview.6.56

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref
 From Version 6.0.100-preview.6.21313.2 -> To Version 6.0.100-preview.6.21328.1 (parent: Microsoft.Android.Sdk.Windows

* Update dependencies from https://github.com/xamarin/xamarin-macios build 20210629.4

Microsoft.macOS.Sdk , Microsoft.MacCatalyst.Sdk , Microsoft.iOS.Sdk , Microsoft.tvOS.Sdk
 From Version 12.0.100-preview.6.60 -> To Version 12.0.100-preview.6.61

* Enable runtimeconfig.json support

We should no longer need to set `$(GenerateRuntimeConfigurationFiles)` to `false`.

* Install `microsoft-net-runtime-maccatalyst` manually

Context: https://github.com/xamarin/xamarin-macios/blob/a64b030fcc06da4a12b0b7e3580c9d349c14daaf/dotnet/targets/WorkloadManifest.MacCatalyst.template.json

Currently, the build fails with:

    error NETSDK1147: To build this project, the following workloads must be installed: microsoft-net-runtime-maccatalyst

It appears we are missing an `extends` for some xamarin-macios workloads.

* Revert "Install `microsoft-net-runtime-maccatalyst` manually"

This reverts commit 7e10ac4ab0d6efff5254e21f91284ee06bb4dd50.

* Manually patch MacCatalyst & iOS workload files

Context: https://github.com/dotnet/runtime/blob/d4baa2bd2b009cdd0886bba925ce32517041bfa0/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.targets

Previously I just tried installing an extra workload:

     Workload with id microsoft-net-runtime-maccatalyst is not supported on this platform.

This workload will not install on Windows. For now I can just patch
the `WorkloadManifest.json` from xamarin/xamarin-macios to depend on
the missing workload.

Even after this, usage of `Microsoft.NETCore.App.Runtime.AOT.Cross` in
the dotnet/runtime `WorkloadManifest.targets` fails on Windows:

     <Import Project="Sdk.props" Sdk="Microsoft.NETCore.App.Runtime.AOT.Cross.maccatalyst" />
     ...
     <Import Project="Sdk.props" Sdk="Microsoft.NETCore.App.Runtime.AOT.Cross.ios-arm" />
     <Import Project="Sdk.props" Sdk="Microsoft.NETCore.App.Runtime.AOT.Cross.ios-arm64" />

I can manually patch these files with a condition to not do this on
Windows.

* Set %TMP% and %TEMP% in another spot

* For now, include missing workload in maui-maccatalyst

* Update dependencies from https://github.com/xamarin/xamarin-android build 6.0.1xx-preview6-3ed60bd3e4728f2ee08c6ceae1091d476743b5f0-1

Microsoft.Android.Sdk.Windows
 From Version 30.0.100-preview.6.51 -> To Version 30.0.100-preview.6.58

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref
 From Version 6.0.100-preview.6.21313.2 -> To Version 6.0.100-preview.6.21328.1 (parent: Microsoft.Android.Sdk.Windows

* Update dependencies from https://github.com/xamarin/xamarin-macios build 20210630.10

Microsoft.macOS.Sdk , Microsoft.MacCatalyst.Sdk , Microsoft.iOS.Sdk , Microsoft.tvOS.Sdk
 From Version 12.0.100-preview.6.60 -> To Version 12.0.100-preview.6.62

* Revert "For now, include missing workload in maui-maccatalyst"

This reverts commit 6eeee590ed60b8b082c8397cfd7b00ab67c02654.

* No longer need to patch microsoft.net.sdk.maccatalyst/WorkloadManifest.json

* Use --temp-dir switch instead of $TMP/$TEMP env vars

* [essentials] use AssemblyMetadata w/ IsTrimmable instead of Linkersafe

Context: https://github.com/xamarin/xamarin-android/pull/6054

This solves the warning (that is turned into an error):

    src/Essentials/src/AssemblyInfo/AssemblyInfo.android.cs(3,12): error CS0618: 'LinkerSafeAttribute' is obsolete: 'For .NET 6+, please use: [assembly: global::System.Reflection.AssemblyMetadata("IsTrimmable", "True")]'

* Update dependencies from https://github.com/xamarin/xamarin-android build 6.0.1xx-preview6-52a34e9c48bad7ae2cb16d28af9700f605163dda-1

Microsoft.Android.Sdk.Windows
 From Version 30.0.100-preview.6.51 -> To Version 30.0.100-preview.6.60

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref
 From Version 6.0.100-preview.6.21313.2 -> To Version 6.0.100-preview.6.21329.10 (parent: Microsoft.Android.Sdk.Windows

* Update dependencies from https://github.com/xamarin/xamarin-android build 6.0.1xx-preview6-ac0333b7828fd72de2afb43c67d8212f18d5be43-1

Microsoft.Android.Sdk.Windows
 From Version 30.0.100-preview.6.51 -> To Version 30.0.100-preview.6.61

Dependency coherency updates

Microsoft.Dotnet.Sdk.Internal,Microsoft.NETCore.App.Ref
 From Version 6.0.100-preview.6.21313.2 -> To Version 6.0.100-preview.6.21351.1 (parent: Microsoft.Android.Sdk.Windows

Co-authored-by: dotnet-maestro[bot] <dotnet-maestro[bot]@users.noreply.github.com>
Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>
Co-authored-by: Rui Marinho <me@ruimarinho.net>
Co-authored-by: Matthew Leibowitz <mattleibow@live.com>