[android] fix `Android` namespace conflicts (#28771)
Context: https://github.com/dotnet/android/pull/9973

We introduced a new `internal` type in `Mono.Android.dll`:

    namespace Microsoft.Android.Runtime;

    class ManagedValueManager : JniRuntime.JniValueManager

Causes various C# compiler errors in dotnet/maui:

    D:\src\maui\src\Essentials\src\AppActions\AppActions.shared.cs(62,28):
    error CS0234: The type or namespace name 'Content' does not exist in the namespace 'Microsoft.Android' (are you missing an assembly reference?)

At some point in .NET 10 (or future), we will likely introduce a
*public* type in `Microsoft.Android` namespace.

This means MAUI's codebase will need to be fixed in a .NET 10
timeframe, so instead of:

    Android.Content.Context content;

This works:

    using Android.Content;
    //...
    Context content;

Because the `using Android.Content;` directive is scoped *outside* of
a `Microsoft.*` namespace.

We don't anticipate this to be a problem with customers, because they
aren't writing code in `Microsoft.*` namespaces.

I generally took the approach:

* Use `using Android.Content;` if possible.

* Use `global::` if that caused other conflicts.

* Use `using AView = Android.Views.View;` in Microsoft.Maui.Controls
  or other places this is commonly used.

* Update `#if __ANDROID__` to `#if ANDROID` in a few places.