[android] fix DI registration for Frame, ListView, TableView (#16989)
This partially reverts 8caaa6df.

When running:

    .\bin\dotnet\dotnet.exe build src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj -f net7.0-android -t:Run

The app crashes on the "Compatibility" screen with:

    System.InvalidOperationException: No service for type 'Android.Content.Context' has been registered.

These are caused by the change:

    --handlersCollection.AddHandler(typeof(Frame), typeof(Handlers.Compatibility.FrameRenderer));
    ++handlersCollection.AddHandler<Frame>(svc => new Handlers.Compatibility.FrameRenderer(svc.GetRequiredService<Android.Content.Context>()));

It turns out this code path only works because:

1. Microsoft.Extensions.DI throws a `MissingMethodException`

2. MAUI has fallback logic to catch this and call:

    return (IElementHandler)Extensions.DependencyInjection.
        ActivatorUtilities.CreateInstance(mauiContext.Services, handlerType, mauiContext.Context);

`ActivatorUtilities` is part of Microsoft.Extensions.DI.

For now, let's just revert this change for Android for these three
types: `Frame`, `ListView`, and `TableView`.

I spend some time trying to "unwind" this and avoid the
`MissingMethodException` on startup. I couldn't solve it yet, but plan
to come back to it later.