[net9.0] Update preview7 packages (#23809)
* [ci] Update sdk preview7

* [net9.0] Update references for aspnet

* Update sdk

* Update preview7 packages

* dotnet/runtime 8.0.8 feeds

* Fix xamarin/xamarin-macios dependency names

* darc update-dependencies --id 232964

* $(DotNetMaciOSManifestVersionBand) is preview.7

* $(NoWarn) CS0618, for Blazor scenarios

D:\a\_work\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0]
D:\a\_work\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0-maccatalyst\maccatalyst-x64\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-maccatalyst]
D:\a\_work\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0-android\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-android]
D:\a\_work\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0-tizen\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-tizen]
D:\a\_work\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0-ios\iossimulator-x64\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-ios]
D:\a\_work\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0-windows10.0.20348\win10-x64\intermediatexaml\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-windows10.0.20348]
D:\a\_work\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0-windows10.0.19041\win10-x64\intermediatexaml\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-windows10.0.19041]
    388 Warning(s)
    7 Error(s)

* Ignore Apple API changes

These are marked obsolete, but they likely "still work" for now:

/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(146,4): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(154,4): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'NetworkReachability.SetNotification(NetworkReachability.Notification)' is obsoleted on: 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(145,4): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'NetworkReachability.SetNotification(NetworkReachability.Notification)' is obsoleted on: 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(155,4): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/WebAuthenticator/WebAuthenticator.ios.tvos.cs(75,11): error CA1422: This call site is reachable on: 'MacCatalyst' 12.0 and later. 'ASWebAuthenticationSession' is obsoleted on: 'maccatalyst' 17.4 and later (Use the 'ASWebAuthenticationSessionCallback' overload instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs(32,17): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'UIImpactFeedbackGenerator' is obsoleted on: 'maccatalyst' 17.5 and later (Use 'GetFeedbackGenerator' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs(24,17): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'UIImpactFeedbackGenerator' is obsoleted on: 'maccatalyst' 17.5 and later (Use 'GetFeedbackGenerator' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(155,4): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(154,4): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'NetworkReachability.SetNotification(NetworkReachability.Notification)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(145,4): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'NetworkReachability.SetNotification(NetworkReachability.Notification)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(146,4): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs(24,17): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'UIImpactFeedbackGenerator' is obsoleted on: 'ios' 17.5 and later (Use 'GetFeedbackGenerator' method instead.), 'maccatalyst' 17.5 and later (Use 'GetFeedbackGenerator' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs(32,17): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'UIImpactFeedbackGenerator' is obsoleted on: 'ios' 17.5 and later (Use 'GetFeedbackGenerator' method instead.), 'maccatalyst' 17.5 and later (Use 'GetFeedbackGenerator' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/WebAuthenticator/WebAuthenticator.ios.tvos.cs(75,11): error CA1422: This call site is reachable on: 'iOS' 12.0 and later, 'maccatalyst' 13.0 and later. 'ASWebAuthenticationSession' is obsoleted on: 'ios' 17.4 and later (Use the 'ASWebAuthenticationSessionCallback' overload instead.), 'maccatalyst' 17.4 and later (Use the 'ASWebAuthenticationSessionCallback' overload instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
    0 Warning(s)
    14 Error(s)

* Two more Apple API changes

* use branded macios net9.0p7 versions

* Update sdk and android

* Update macios version

* Update to sdk in validation and aspnet

* Update iOS

* Bump macios

---------

Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>
Co-authored-by: Alex Soto <alex@soto.dev>