Build with .NET 10 successfully (#27103)
* Build with .NET 10 successfully

Changes required:

* Get appropriate `net9` branded workload manifests from dotnet/runtime

* Fix NuGet package downgrades:

    src\SingleProject\Resizetizer\src\Resizetizer.csproj : error NU1605:
      Warning As Error: Detected package downgrade: System.Runtime.CompilerServices.Unsafe from 6.1.0 to 6.0.0. Reference the package directly from the project to select a different version.
       Microsoft.Maui.Resizetizer -> Microsoft.Bcl.AsyncInterfaces 10.0.0-alpha.1.25058.4 -> System.Threading.Tasks.Extensions 4.6.0 -> System.Runtime.CompilerServices.Unsafe (>= 6.1.0)
       Microsoft.Maui.Resizetizer -> System.Runtime.CompilerServices.Unsafe (>= 6.0.0)
    src\Core\src\Core.csproj : error NU1605:
      Warning As Error: Detected package downgrade: System.Numerics.Vectors from 4.6.0 to 4.5.0. Reference the package directly from the project to select a different version.
       Microsoft.Maui.Core -> Microsoft.Extensions.Logging.Abstractions 10.0.0-alpha.1.25057.17 -> System.Memory 4.6.0 -> System.Numerics.Vectors (>= 4.6.0)
       Microsoft.Maui.Core -> System.Numerics.Vectors (>= 4.5.0)

* Update to iOS, tvOS, MacCatalyst 18.2

    10.0.100-alpha.1.25059.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(259,5):
    error NETSDK1140:
        18.0 is not a valid TargetPlatformVersion for MacCatalyst. Valid versions include:
        18.2
    10.0.100-alpha.1.25059.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(259,5):
    error NETSDK1140:
        18.0 is not a valid TargetPlatformVersion for iOS. Valid versions include:
        18.2

* Temporarily ignore `CS9270`:
  * https://github.com/dotnet/roslyn/pull/76312
  * https://github.com/dotnet/roslyn/issues/72133

    artifacts\obj\Controls.Core\Debug\net10.0\Microsoft.Maui.Controls.BindingSourceGen\Microsoft.Maui.Controls.BindingSourceGen.BindingSourceGenerator\D--src-maui-src-Controls-src-Core-BindableLayout-BindableLayout.cs-GeneratedBindingInterceptors-235-10.g.cs(43,4): error CS9270: 'InterceptsLocationAttribute(string, int, int)' is not supported. Move to 'InterceptableLocation'-based generation of these attributes instead. (https://github.com/dotnet/roslyn/issues/72133)
    artifacts\obj\Controls.Core\Debug\net10.0\Microsoft.Maui.Controls.BindingSourceGen\Microsoft.Maui.Controls.BindingSourceGen.BindingSourceGenerator\D--src-maui-src-Controls-src-Core-ContentConverter.cs-GeneratedBindingInterceptors-72-13.g.cs(43,4): error CS9270: 'InterceptsLocationAttribute(string, int, int)' is not supported. Move to 'InterceptableLocation'-based generation of these attributes instead. (https://github.com/dotnet/roslyn/issues/72133)
    artifacts\obj\Controls.Core\Debug\net10.0\Microsoft.Maui.Controls.BindingSourceGen\Microsoft.Maui.Controls.BindingSourceGen.BindingSourceGenerator\D--src-maui-src-Controls-src-Core-ContentConverter.cs-GeneratedBindingInterceptors-77-13.g.cs(43,4): error CS9270: 'InterceptsLocationAttribute(string, int, int)' is not supported. Move to 'InterceptableLocation'-based generation of these attributes instead. (https://github.com/dotnet/roslyn/issues/72133)

* iOS API changes:

    error CS0618: 'CLLocation.AccurracyBestForNavigation' is obsolete: 'Use 'AccuracyBestForNavigation' instead.'

    Screenshot.ios.cs(57,69): error CS8602: Dereference of a possibly null reference.

    Platform\iOS\KeyboardAutoManagerScroll.cs(867,55): error CS8602: Dereference of a possibly null reference.

    src\Core\src\Platform\iOS\MauiSwipeView.cs(601,8): error CS8625: Cannot convert null literal to non-nullable reference type.
    src\Core\src\Platform\iOS\MauiSwipeView.cs(634,8): error CS8625: Cannot convert null literal to non-nullable reference type.

    ResignFirstResponderTouchGestureRecognizer.iOS.cs(70,12): error CS8600: Converting null literal or possible null value to non-nullable type.

    GesturePlatformManager.iOS.cs(282,21): error CS8602: Dereference of a possibly null reference.

Most notably:

* `UIView.Window` can be null.

* Typo in API fixed `AccurracyBestForNavigation` -> `AccuracyBestForNavigation`

* Disable tizen net10.0 temporarily

* TargetFramework=net10.0

* TargetFramework=net10.0

* Unused yaml: `TestTargetFrameworks`

* Update RunnerGenerator.cs

Workaround: https://github.com/dotnet/android/commit/715a36af86c68bac623a4174477165bb14b4c371

* Put iOS simulator versions back to 18.0

* Update RunnerGenerator.cs

* Update xUnitSharedAttributes.cs

    D:\src\maui\src\TestUtils\src\TestShared\xUnitSharedAttributes.cs(75,89): error CS0117: 'DynamicallyAccessedMemberTypes' does not contain a definition for 'PublicParameterlessConstructors'
    D:\src\maui\src\TestUtils\src\TestShared\xUnitSharedAttributes.cs(83,63): error CS0117: 'DynamicallyAccessedMemberTypes' does not contain a definition for 'PublicParameterlessConstructors'

* Update Core.DeviceTests.Shared.csproj

* Update RunnerGenerator.cs

* Remove Tizen project

* Update ios.cake

* Update Core.DeviceTests.csproj

* Update android

* Update xcode

* Disable trimming warnings for now

* [iOS] Move to 18.2 simulators

* Ignore more warnings

* Ignore more warnings

* Update MainViewController.cs

* Ignore more warnings

* Disable more warnings

* Update xUnitSharedAttributes.cs

* Put trimmer warnings back

* EnableTrimAnalyzer=false for test projects across repo

* Make `EnableTizen()` a no-op

* Update Controls.DeviceTests.csproj

* Install `mobile-librarybuilder-net9`

Context: https://github.com/xamarin/xamarin-macios/pull/21848/commits/cb1340221774ba9af226ac71a5aef551d765ee21

* Update WindowsTemplateTest.cs

* `mobile-librarybuilder-net9` on test lanes

* Update Essentials.Sample.csproj

* See if newer .NET SDK fixes maui-blazor

Context: https://github.com/dotnet/sdk/compare/26fd6d135ae2605cf618caeffe83b3be5e314ac5...60e9a46917ff91cc570272ecc83249497c99a79f

I see a dotnet/aspnetcore bump in the diff.

* Essentials.Sample.csproj is a "sample project"

* > darc update-dependencies --id 252455

* Revert "Update RunnerGenerator.cs"

This reverts commit b9f32f6b0037a48e9833c72a9ab2c1840e18e788.

* Revert "Update RunnerGenerator.cs"

This reverts commit 9f6d36dff6f4c878f3c97ed47dc46655ede8e5e4.

* Revert "Update RunnerGenerator.cs"

This reverts commit 0f43f7def0e4df427e589814de674c8a314d1d50.

* darc update-dependencies --id 252613

* darc update-dependencies --coherency-only

* Update Version.Details.xml

* SuppressTrimAnalysisWarnings=true for test/sample projects

* Update Controls.DeviceTests.csproj

* Revert "Update Controls.DeviceTests.csproj"

This reverts commit 5ce03907e3701932a8678c2d1d0687b871a66b28.

* Disable iOS test for now

* Update provision.yml

* Update versions

* Update versions

* Revert "Update provision.yml"

This reverts commit 33a8ee569ca6d31950829375f4be05aad1235c00.

* Update LabelExtensions.cs

* Update ButtonTests.iOS.cs

* Try these new aspnet versions

* Update AssemblyInfoTests.cs

* $(TrimmerSingleWarn)=false

* Update MauiBlazorWebView.DeviceTests.csproj

* $(IsTestProject) -> $(MauiTestProject)

The old name conflicts with dotnet/arcade.

* Update Core.UnitTests.csproj

* Update MacTemplateTest.cs

* Update MacTemplateTest.cs

* Revert "Update MacTemplateTest.cs"

This reverts commit 7ed2b89e645bfa996073c0d3990fbd7d276ceb13.

* Revert "Update MacTemplateTest.cs"

This reverts commit 882c45e1eeed5d8afc712ddae1d99d6b76632f4f.

* EnableTrimAnalyzer=false for default projects

Context: https://github.com/xamarin/xamarin-macios/pull/21351

This will avoid some of the fallout of the above PR.

* $(EnableTrimAnalyzer) take 2

* Update TestUtils.DeviceTests.Sample.csproj

* Update Microsoft.Maui.Controls.Common.targets

* Update Microsoft.Maui.Controls.Common.targets

* Update SimpleTemplateTest.cs

* Update Microsoft.Maui.Controls.Common.targets

* System.Text.Json.Serialization.Converters.EnumConverterFactory warning is gone

* Potential fix for M.E.DI failure

Fixes?

    [15:12:46.2484560] 2025-01-22 15:12:46.242709-0800 RunOniOSmauiRel1586373188[97228:54445246] Received unhandled Objective-C exception that was marshalled from a managed exception: A suitable constructor for type 'Microsoft.Maui.Hosting.FontsMauiAppBuilderExtensions+FontInitializer' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor. (System.InvalidOperationException)
[15:12:46.2484780]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache, ServiceIdentifier, Type, CallSiteChain) + 0x4de
[15:12:46.2485210]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor, ServiceIdentifier, CallSiteChain, Int32) + 0x1a5
[15:12:46.2485640]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(ServiceIdentifier, CallSiteChain) + 0x42f
[15:12:46.2485930]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain) + 0xfb
[15:12:46.2486100]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier, CallSiteChain) + 0x92
[15:12:46.2486220]    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier) + 0x68
[15:12:46.2486330]    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2) + 0xdc
[15:12:46.2486790]    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope) + 0x39
[15:12:46.2486900]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider, Type) + 0x3d
[15:12:46.2487000]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider) + 0x2f
[15:12:46.2487100]    at Microsoft.Maui.MauiContextExtensions.InitializeAppServices(MauiApp) + 0x1b
[15:12:46.2487190]    at Microsoft.Maui.Hosting.MauiAppBuilder.Build() + 0x67
[15:12:46.2487420]    at Microsoft.Maui.MauiUIApplicationDelegate.WillFinishLaunching(UIApplication application, NSDictionary launchOptions) + 0x44
[15:12:46.2487530]    at RunOniOSmauiRel1586373188!<BaseAddress>+0xe200a

* Revert "Potential fix for M.E.DI failure"

This reverts commit 802e4c15674612e0af2bc4e07fefd63a8b622554.

* Update versions with CoherentParentDependency

* Update versions with coherent Microsoft.JSInterop

* Use strongly-typed Transient() for M.E.DI

* MauiVersionCurrent / MauiVersionPrevious

* Update FontsMauiAppBuilderExtensions.cs

* Revert "Update FontsMauiAppBuilderExtensions.cs"

This reverts commit 6b8e48ad907cb184fd6e5b471bbe290a309cfdb8.

* Revert "Use strongly-typed Transient() for M.E.DI"

This reverts commit b0e0e45fd76d5645e480321f42f56386a1285384.

* Comment a few NativeAOT tests

---------

Co-authored-by: Rui Marinho <me@ruimarinho.net>