[templates] fix maui-blazor template (#1415)
In 9d53aea8, I inadvertently broke the `maui-blazor` template. It
crashes on startup with:

    System.InvalidOperationException: Could not load the embedded file manifest 'Microsoft.Extensions.FileProviders.Embedded.Manifest.xml' for assembly 'foo'.

It turns out that `Microsoft.Extensions.FileProviders.Embedded` is
also missing the `buildTransitive` folder--the same problem we saw
with the ProjectReunion packages:

https://www.nuget.org/packages/Microsoft.Extensions.FileProviders.Embedded/6.0.0-preview.5.21301.17

Contents:

    build
    buildMultiTargeting
    lib
    package
    tasks
    Microsoft.Extensions.FileProviders.Embedded.nuspec
    Icon.png

Adding the package to the `.csproj` directly solves this issue, so we
have to include this in the `maui-blazor` template.