[workload] fix Microsoft.Maui.Extensions package (#1350)
Since 4ef29fb3, using the workload in an app causes a crash on startup:

     System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.

I missed this assembly, which is a dependency of
`Microsoft.Extensions.DependencyInjection`.

In total, the following were missing:

* `Microsoft.Extensions.Configuration.Abstractions`
* `Microsoft.Extensions.DependencyInjection.Abstractions`
* `Microsoft.Extensions.FileProviders.Abstractions`

I also included the `*.xml` documentation files for these assemblies
that were left out by mistake.