[android] update to the latest AndroidX packages (#5588)
* [android] update to the latest AndroidX packages

Context: https://github.com/dotnet/maui/pull/5305
Fixes: https://github.com/xamarin/AndroidX/issues/509

Update to the latest AndroidX packages, so we also use the latest
Xamarin.Google.Guava.ListenableFuture

This currently has build failures:

  src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs(145,41): error CS1061: 'NavController' does not contain a definition for 'BackStack' and no accessible extension method 'BackStack' accepting a first argument of type 'NavController' could be found (are you missing a using directive or an assembly reference?)
  src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs(188,48): error CS1061: 'NavController' does not contain a definition for 'BackStack' and no accessible extension method 'BackStack' accepting a first argument of type 'NavController' could be found (are you missing a using directive or an assembly reference?)
  src\Core\src\Platform\Android\Navigation\StackNavigationManager.cs(245,51): error CS1061: 'NavController' does not contain a definition for 'BackStack' and no accessible extension method 'BackStack' accepting a first argument of type 'NavController' could be found (are you missing a using directive or an assembly reference?)

Looking at:

    ~\.nuget\packages\xamarin.androidx.navigation.runtime\2.4.1\lib\net6.0-android31.0\Xamarin.AndroidX.Navigation.Runtime.dll

I can't find:

    [Register("androidx/navigation/NavController", DoNotGenerateAcw = true)]
    public class NavController : Object
    {
        public unsafe virtual IDeque BackStack
        {
            [Register("getBackStack", "()Ljava/util/Deque;", "GetGetBackStackHandler")]
            get;

But it's not documented here either:

https://developer.android.com/reference/androidx/navigation/NavController

* - replace with BackQueue

* - fix tests

* $(NoWarn) XA4218

* $(MSBuildWarningsAsMessages) I mean

Co-authored-by: Shane Neuville <shneuvil@microsoft.com>